#!/usr/bin/env bash

pip2 install /opt/storage_piCopilot-wifi/packetEssentials-1.4.6.tar.gz
pip2 install /opt/storage_piCopilot-wifi/pbkdf2-1.3.tar.gz
pip2 install /opt/storage_piCopilot-wifi/pyDot11-2.1.0.tar.gz
pip2 install /opt/storage_piCopilot-wifi/pycryptodomex-3.4.5.tar.gz
pip2 install /opt/storage_piCopilot-wifi/rc4-0.2.tar.gz
pip2 install /opt/storage_piCopilot-wifi/scapy-2.4.3rc4.dev1.tar.gz

pip3 install /opt/storage_piCopilot-wifi/packetEssentials-1.4.6.tar.gz
pip3 install /opt/storage_piCopilot-wifi/pbkdf2-1.3.tar.gz
pip3 install /opt/storage_piCopilot-wifi/pyDot11-2.1.0.tar.gz
pip3 install /opt/storage_piCopilot-wifi/pycryptodomex-3.4.5.tar.gz
pip3 install /opt/storage_piCopilot-wifi/rc4-0.2.tar.gz
pip3 install /opt/storage_piCopilot-wifi/scapy-2.4.3rc4.dev1.tar.gz
