#!/usr/bin/env bash

## chown for postgres
chown -R postgres /opt/piCopilot-idrop/logs

## Start supervisor daemon
systemctl start supervisor
systemctl enable supervisor

## Ensure postgresql running
systemctl enable postgresql
systemctl start postgresql

